services:
  docs:
    image: civil_registry_local_docs
    container_name: civil_registry_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./civil_registry:/app/civil_registry:z
    ports:
      - '9000:9000'
    command: /start-docs
