# Generated by Django 5.0.10 on 2025-01-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_number", models.CharField(blank=True, default="", max_length=14)),
                ("detail", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("request_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("request_method", models.CharField(max_length=10)),
                ("path", models.CharField(db_index=True, max_length=255)),
                ("user_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("status_code", models.IntegerField()),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("processing_time", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
